### PR TITLE
Use sample weights in training

### PR DESCRIPTION
**Pull request by jandom**
- split out a utils.py script,
- improvements to plotting.

### CODE REVIEW

**Review by ktamiola — COMMENTED** [review]
'Lambda function because i can', you are adorable...

**Review by ktamiola — COMMENTED** [review]
The `model/*` was a good idea. I would definitely prefer to have a dedicated output directory.

**Comment by ktamiola** [comment]
Examples have passed the testing at my end. Shall we merge or rebase?

**Comment by jandom** [comment]
It's a matter of style 

- if you wanna stress that this branch was moving independently of changes on master, do the merge

- if you wanna stress that it's a stand-alone independent but big feature, rebase

- if you wanna stress that it's stand alone and small, rebase and squash

**Pull request merged**
